### ISSUE TITLE
Failed to Build for Android on Go v1.23.1 Using anet Package

### ISSUE THREAD

**Issue by ja7ad** [wlynxg/anet#7]
Hello, Thank you for your package.

I'm encountering a build error when attempting to compile a Go project targeting Android (GOOS=android, GOARCH=arm64) using the `anet` package. The following code reproduces the issue:

```go
package main

import (
	"fmt"
	"log"
	"github.com/wlynxg/anet"
)

func main() {
	i, err := anet.Interfaces()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(i)
}
```

**Command used:**

```bash
CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -ldflags "-s -w -checklinkname=0" main.go
```

**Error:**

```
# command-line-arguments
./main.go:10:17: undefined: anet.Interfaces
```

It appears the `anet.Interfaces` function is not available during the build process. This issue might be related to how the package handles platform-specific code.

**Environment:**

- Go version: 1.23.1
- Target platform: Android (ARM64)
- Package: `anet` (latest version)

Any insights or solutions would be appreciated.

**Comment by wlynxg** [comment]
In order to automatically obtain the Android version number, CGO is used in the Android code. 
The code is at: https://github.com/wlynxg/anet/blob/a79b5ca41e539e26fc7028a9f82ac92b58ef50df/interface_android.go#L3

**Comment by wlynxg** [comment]
Perhaps we should support manually setting the Android version without using CGO? @bobrofon

**Comment by ja7ad** [comment]
> In order to automatically obtain the Android version number, CGO is used in the Android code. The code is at:
> 
> https://github.com/wlynxg/anet/blob/a79b5ca41e539e26fc7028a9f82ac92b58ef50df/interface_android.go#L3

We build android version on older version of go, without any issue on build.

https://github.com/pactus-project/pactus/releases/tag/v1.4.0

Package used: 

- https://github.com/pactus-project/pactus/blob/a505f9c07f840ed8d5c1c862851cfa55c0176401/go.mod#L137C2-L137C27

- https://github.com/pion/transport/blob/ea4fc430cce8423896e78100736a61f3712f053d/go.mod#L8

**Comment by bobrofon** [comment]
> We build android version on older version of go, without any issue on build.

I reproduced the same build error on go 1.22.7. It doesn't seem that the go version is relevant.

**Comment by b00f** [comment]
It make sense, since I can't see `anet` in older version of Pactus [here](https://github.com/pactus-project/pactus/blob/a505f9c07f840ed8d5c1c862851cfa55c0176401/go.sum)
This way we can't support Android anymore!?

**Comment by bobrofon** [comment]
>  This way we can't support Android anymore!?

There is an open PR https://github.com/wlynxg/anet/pull/8 fixing this issue.
Or you can just build `Pactus` with `anet` from this commit 4d6caa22d546a3714f046a8f837aed36afd71dc4. It should work as well.

**Comment by b00f** [comment]
Thanks for the quick response and for promptly fixing the issue.
